import { MockDatabase } from "./types";

// Initial seed data for local development
export const initialMockData: MockDatabase = {
  users: [
    {
      id: "user-consumer-1",
      email: "consumer@test.com",
      password: "password123", // Plain text for mock (never do this in production!)
      name: "Ahmed Khan",
      phone: "(510) 555-0100",
      role: "CONSUMER",
      image: null,
      emailVerified: new Date(),
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    {
      id: "user-business-1",
      email: "owner@test.com",
      password: "password123",
      name: "Fatima Ali",
      phone: "(510) 555-0200",
      role: "BUSINESS_OWNER",
      image: null,
      emailVerified: new Date(),
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    {
      id: "user-admin-1",
      email: "admin@test.com",
      password: "password123",
      name: "Admin User",
      phone: "(510) 555-0300",
      role: "ADMIN",
      image: null,
      emailVerified: new Date(),
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
  ],

  businesses: [
    {
      id: "biz-1",
      ownerId: "user-business-1",
      name: "Al-Noor Halal Market",
      slug: "al-noor-halal-market",
      description: "Your trusted source for fresh halal meat, groceries, and Middle Eastern foods in Fremont. Family-owned and operated since 2015.",
      category: "HALAL_FOOD",
      address: "39100 Argonaut Way",
      city: "Fremont",
      state: "CA",
      zipCode: "94538",
      latitude: 37.5485,
      longitude: -121.9886,
      phone: "(510) 555-1234",
      email: "info@alnoormarket.com",
      website: "https://alnoormarket.com",
      hours: {
        monday: { open: "09:00", close: "20:00" },
        tuesday: { open: "09:00", close: "20:00" },
        wednesday: { open: "09:00", close: "20:00" },
        thursday: { open: "09:00", close: "20:00" },
        friday: { open: "09:00", close: "21:00" },
        saturday: { open: "09:00", close: "21:00" },
        sunday: { open: "10:00", close: "19:00" },
      },
      services: ["Fresh Halal Meat", "Groceries", "Bakery Items", "Prepared Foods"],
      status: "PUBLISHED",
      prayerTimes: null,
      jummahTime: null,
      aidServices: [],
      externalUrl: null,
      createdAt: new Date("2024-01-15"),
      updatedAt: new Date("2024-01-15"),
      tags: ["MUSLIM_OWNED", "HALAL_VERIFIED"],
      photos: [],
    },
    {
      id: "biz-2",
      ownerId: "user-business-1",
      name: "Islamic Center of Fremont",
      slug: "islamic-center-of-fremont",
      description: "A welcoming community masjid serving the Fremont area. Daily prayers, Jummah, weekend school, and community events.",
      category: "MASJID",
      address: "38350 Civic Center Dr",
      city: "Fremont",
      state: "CA",
      zipCode: "94536",
      latitude: 37.5502,
      longitude: -121.9816,
      phone: "(510) 555-5678",
      email: "info@icfremont.org",
      website: "https://icfremont.org",
      hours: {
        monday: { open: "05:00", close: "22:00" },
        tuesday: { open: "05:00", close: "22:00" },
        wednesday: { open: "05:00", close: "22:00" },
        thursday: { open: "05:00", close: "22:00" },
        friday: { open: "05:00", close: "22:00" },
        saturday: { open: "05:00", close: "22:00" },
        sunday: { open: "05:00", close: "22:00" },
      },
      services: ["Daily Prayers", "Jummah", "Weekend School", "Community Events"],
      status: "PUBLISHED",
      prayerTimes: {
        fajr: "05:30",
        dhuhr: "13:00",
        asr: "16:30",
        maghrib: "18:45",
        isha: "20:00",
      },
      jummahTime: "13:15",
      aidServices: [],
      externalUrl: null,
      createdAt: new Date("2024-01-10"),
      updatedAt: new Date("2024-01-10"),
      tags: ["PRAYER_SPACE", "SISTERS_FRIENDLY", "KID_FRIENDLY", "WHEELCHAIR_ACCESSIBLE"],
      photos: [],
    },
    {
      id: "biz-3",
      ownerId: "user-business-1",
      name: "Bay Area Auto Repair - Pending Review",
      slug: "bay-area-auto-repair",
      description: "Muslim-owned auto repair shop specializing in all makes and models. Honest service, fair prices.",
      category: "AUTO_REPAIR",
      address: "4500 Cushing Pkwy",
      city: "Fremont",
      state: "CA",
      zipCode: "94538",
      latitude: 37.5342,
      longitude: -121.9711,
      phone: "(510) 555-9999",
      email: null,
      website: null,
      hours: null,
      services: ["Oil Change", "Brake Repair", "Engine Diagnostics", "Tire Service"],
      status: "PENDING_REVIEW",
      prayerTimes: null,
      jummahTime: null,
      aidServices: [],
      externalUrl: null,
      createdAt: new Date("2024-01-20"),
      updatedAt: new Date("2024-01-20"),
      tags: ["MUSLIM_OWNED"],
      photos: [],
    },
  ],

  reviews: [
    {
      id: "review-1",
      businessId: "biz-1",
      userId: "user-consumer-1",
      rating: 5,
      text: "Excellent halal market! Fresh meat, friendly staff, and great selection of Middle Eastern products. Highly recommend!",
      tags: { serviceQuality: true, cleanliness: true, authentic: true },
      helpfulCount: 3,
      createdAt: new Date("2024-01-18"),
      updatedAt: new Date("2024-01-18"),
      photos: [],
    },
    {
      id: "review-2",
      businessId: "biz-2",
      userId: "user-consumer-1",
      rating: 5,
      text: "Beautiful masjid with excellent facilities. The sisters' section is spacious and well-maintained. Great khutbahs every Friday!",
      tags: { cleanliness: true, familyFriendly: true, friendly: true },
      helpfulCount: 5,
      createdAt: new Date("2024-01-12"),
      updatedAt: new Date("2024-01-12"),
      photos: [],
    },
  ],

  scrapedBusinesses: [
    {
      id: "scraped-1",
      name: "Zabiha Halal Restaurant",
      address: "43433 Mission Blvd",
      city: "Fremont",
      state: "CA",
      zipCode: "94539",
      latitude: 37.5426,
      longitude: -121.9302,
      phone: "(510) 555-7890",
      email: null,
      website: "https://zabiharestaurant.com",
      category: "RESTAURANT",
      description: "Pakistani and Indian halal cuisine. Buffet available daily.",
      services: ["Dine-in", "Takeout", "Catering"],
      suggestedTags: ["HALAL_VERIFIED", "MUSLIM_OWNED"],
      source: "google_maps",
      sourceUrl: "https://maps.google.com/example",
      confidence: 95,
      signals: ["zabiha", "halal", "pakistani", "muslim owner mention in reviews"],
      status: "PENDING",
      reviewedBy: null,
      reviewNote: null,
      scrapedAt: new Date("2024-01-21"),
      reviewedAt: null,
    },
    {
      id: "scraped-2",
      name: "Masjid Warithuddin Mohammed",
      address: "5600 Bernal Ave",
      city: "Pleasanton",
      state: "CA",
      zipCode: "94566",
      latitude: 37.6624,
      longitude: -121.8747,
      phone: "(925) 555-1111",
      email: "info@masjidwdm.org",
      website: "https://masjidwdm.org",
      category: "MASJID",
      description: "Community masjid in Pleasanton serving the Tri-Valley area.",
      services: ["Daily Prayers", "Jummah", "Islamic Education"],
      suggestedTags: ["PRAYER_SPACE", "SISTERS_FRIENDLY"],
      source: "zabihah",
      sourceUrl: "https://zabihah.com/example",
      confidence: 100,
      signals: ["masjid", "islamic center", "prayer times listed"],
      status: "PENDING",
      reviewedBy: null,
      reviewNote: null,
      scrapedAt: new Date("2024-01-22"),
      reviewedAt: null,
    },
    {
      id: "scraped-3",
      name: "Ahmed's Barber Shop",
      address: "39170 State St",
      city: "Fremont",
      state: "CA",
      zipCode: "94538",
      latitude: 37.5502,
      longitude: -121.9822,
      phone: "(510) 555-2222",
      email: null,
      website: null,
      category: "BARBER_SALON",
      description: "Traditional barber shop with excellent service.",
      services: ["Haircuts", "Beard Trim", "Hot Towel Shave"],
      suggestedTags: ["MUSLIM_OWNED"],
      source: "yelp",
      sourceUrl: "https://yelp.com/example",
      confidence: 70,
      signals: ["owner name: Ahmed", "mentions prayer breaks in reviews"],
      status: "FLAGGED",
      reviewedBy: "user-admin-1",
      reviewNote: "Need to verify Muslim ownership - only indicator is owner's name",
      scrapedAt: new Date("2024-01-20"),
      reviewedAt: new Date("2024-01-21"),
    },
  ],

  conversations: [],
  messages: [],
};
