import { MockDatabase } from "./types";

// Initial seed data for local development
export const initialMockData: MockDatabase = {
  users: [
    {
      id: "user-consumer-1",
      email: "consumer@test.com",
      password: "password123",
      name: "Ahmed Khan",
      phone: "(510) 555-0100",
      role: "CONSUMER",
      image: null,
      emailVerified: new Date(),
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    {
      id: "user-business-1",
      email: "owner@test.com",
      password: "password123",
      name: "Fatima Ali",
      phone: "(510) 555-0200",
      role: "BUSINESS_OWNER",
      image: null,
      emailVerified: new Date(),
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    {
      id: "user-admin-1",
      email: "admin@test.com",
      password: "password123",
      name: "Admin User",
      phone: "(510) 555-0300",
      role: "ADMIN",
      image: null,
      emailVerified: new Date(),
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
  ],

  businesses: [
    {
      id: "biz-1",
      ownerId: "user-business-1",
      name: "Al-Noor Halal Market",
      slug: "al-noor-halal-market",
      description: "Your trusted source for fresh halal meat, groceries, and Middle Eastern foods in Fremont. Family-owned and operated since 2015.",
      shortDescription: "Fresh halal meat and Middle Eastern groceries",
      category: "HALAL_FOOD",
      address: "39100 Argonaut Way",
      city: "Fremont",
      state: "CA",
      zipCode: "94538",
      latitude: 37.5485,
      longitude: -121.9886,
      phone: "(510) 555-1234",
      email: "info@alnoormarket.com",
      website: "https://alnoormarket.com",
      hours: {
        monday: { open: "09:00", close: "20:00" },
        tuesday: { open: "09:00", close: "20:00" },
        wednesday: { open: "09:00", close: "20:00" },
        thursday: { open: "09:00", close: "20:00" },
        friday: { open: "09:00", close: "21:00" },
        saturday: { open: "09:00", close: "21:00" },
        sunday: { open: "10:00", close: "19:00" },
      },
      services: ["Fresh Halal Meat", "Groceries", "Bakery Items", "Prepared Foods"],
      status: "PUBLISHED",
      priceRange: "MODERATE",
      hoursOfOperation: {
        monday: { open: "09:00", close: "20:00" },
        tuesday: { open: "09:00", close: "20:00" },
        wednesday: { open: "09:00", close: "20:00" },
        thursday: { open: "09:00", close: "20:00" },
        friday: { open: "09:00", close: "21:00" },
        saturday: { open: "09:00", close: "21:00" },
        sunday: { open: "10:00", close: "19:00" },
      },
      verificationStatus: "APPROVED",
      verifiedAt: new Date("2024-01-16"),
      verifiedBy: "user-admin-1",
      viewCount: 156,
      claimStatus: "CLAIMED",
      coverImage: null,
      logoImage: null,
      averageRating: 4.8,
      totalReviews: 3,
      ratingBreakdown: { "5": 2, "4": 1, "3": 0, "2": 0, "1": 0 },
      prayerTimes: null,
      jummahTime: null,
      aidServices: [],
      externalUrl: null,
      createdAt: new Date("2024-01-15"),
      updatedAt: new Date("2024-01-15"),
      tags: ["MUSLIM_OWNED", "HALAL_VERIFIED"],
      photos: [],
    },
    {
      id: "biz-2",
      ownerId: "user-business-1",
      name: "Islamic Center of Fremont",
      slug: "islamic-center-of-fremont",
      description: "A welcoming community masjid serving the Fremont area. Daily prayers, Jummah, weekend school, and community events.",
      shortDescription: "Community masjid with daily prayers and Islamic education",
      category: "MASJID",
      address: "38350 Civic Center Dr",
      city: "Fremont",
      state: "CA",
      zipCode: "94536",
      latitude: 37.5502,
      longitude: -121.9816,
      phone: "(510) 555-5678",
      email: "info@icfremont.org",
      website: "https://icfremont.org",
      hours: {
        monday: { open: "05:00", close: "22:00" },
        tuesday: { open: "05:00", close: "22:00" },
        wednesday: { open: "05:00", close: "22:00" },
        thursday: { open: "05:00", close: "22:00" },
        friday: { open: "05:00", close: "22:00" },
        saturday: { open: "05:00", close: "22:00" },
        sunday: { open: "05:00", close: "22:00" },
      },
      services: ["Daily Prayers", "Jummah", "Weekend School", "Community Events"],
      status: "PUBLISHED",
      verificationStatus: "APPROVED",
      verifiedAt: new Date("2024-01-11"),
      verifiedBy: "user-admin-1",
      viewCount: 234,
      claimStatus: "CLAIMED",
      averageRating: 5.0,
      totalReviews: 2,
      ratingBreakdown: { "5": 2, "4": 0, "3": 0, "2": 0, "1": 0 },
      prayerTimes: {
        fajr: "05:30",
        dhuhr: "13:00",
        asr: "16:30",
        maghrib: "18:45",
        isha: "20:00",
      },
      jummahTime: "13:15",
      aidServices: [],
      externalUrl: null,
      createdAt: new Date("2024-01-10"),
      updatedAt: new Date("2024-01-10"),
      tags: ["PRAYER_SPACE", "SISTERS_FRIENDLY", "KID_FRIENDLY", "WHEELCHAIR_ACCESSIBLE"],
      photos: [],
    },
    {
      id: "biz-3",
      ownerId: "user-business-1",
      name: "Bay Area Auto Repair",
      slug: "bay-area-auto-repair",
      description: "Muslim-owned auto repair shop specializing in all makes and models. Honest service, fair prices.",
      shortDescription: "Honest auto repair with fair pricing",
      category: "AUTO_REPAIR",
      address: "4500 Cushing Pkwy",
      city: "Fremont",
      state: "CA",
      zipCode: "94538",
      latitude: 37.5342,
      longitude: -121.9711,
      phone: "(510) 555-9999",
      email: null,
      website: null,
      hours: null,
      services: ["Oil Change", "Brake Repair", "Engine Diagnostics", "Tire Service"],
      status: "PUBLISHED",
      priceRange: "BUDGET",
      verificationStatus: "PENDING",
      viewCount: 45,
      claimStatus: "CLAIMED",
      averageRating: 4.0,
      totalReviews: 1,
      ratingBreakdown: { "5": 0, "4": 1, "3": 0, "2": 0, "1": 0 },
      prayerTimes: null,
      jummahTime: null,
      aidServices: [],
      externalUrl: null,
      createdAt: new Date("2024-01-20"),
      updatedAt: new Date("2024-01-20"),
      tags: ["MUSLIM_OWNED"],
      photos: [],
    },
  ],

  reviews: [
    {
      id: "review-1",
      businessId: "biz-1",
      userId: "user-consumer-1",
      bookingId: null,
      rating: 5,
      title: "Excellent Halal Market!",
      content: "Excellent halal market! Fresh meat, friendly staff, and great selection of Middle Eastern products. Highly recommend!",
      text: "Excellent halal market! Fresh meat, friendly staff, and great selection of Middle Eastern products. Highly recommend!",
      photos: [],
      tags: { serviceQuality: true, cleanliness: true, authentic: true },
      isVerified: false,
      helpfulCount: 3,
      reportCount: 0,
      ownerResponse: "Thank you so much for your kind words! We strive to provide the best quality products and service.",
      respondedAt: new Date("2024-01-19"),
      status: "PUBLISHED",
      createdAt: new Date("2024-01-18"),
      updatedAt: new Date("2024-01-18"),
    },
    {
      id: "review-2",
      businessId: "biz-2",
      userId: "user-consumer-1",
      bookingId: null,
      rating: 5,
      title: "Beautiful Masjid",
      content: "Beautiful masjid with excellent facilities. The sisters' section is spacious and well-maintained. Great khutbahs every Friday!",
      text: "Beautiful masjid with excellent facilities. The sisters' section is spacious and well-maintained. Great khutbahs every Friday!",
      photos: [],
      tags: { cleanliness: true, familyFriendly: true, friendly: true },
      isVerified: false,
      helpfulCount: 5,
      reportCount: 0,
      status: "PUBLISHED",
      createdAt: new Date("2024-01-12"),
      updatedAt: new Date("2024-01-12"),
    },
    {
      id: "review-3",
      businessId: "biz-1",
      userId: "user-admin-1",
      bookingId: null,
      rating: 4,
      title: "Great Selection",
      content: "Great selection of products. Prices are reasonable. Only suggestion would be to extend Sunday hours.",
      text: "Great selection of products. Prices are reasonable. Only suggestion would be to extend Sunday hours.",
      photos: [],
      isVerified: false,
      helpfulCount: 1,
      reportCount: 0,
      status: "PUBLISHED",
      createdAt: new Date("2024-01-22"),
      updatedAt: new Date("2024-01-22"),
    },
    {
      id: "review-4",
      businessId: "biz-3",
      userId: "user-consumer-1",
      bookingId: "booking-1",
      rating: 4,
      title: "Good Service",
      content: "Got my oil changed here. Quick service and fair price. Will come back again.",
      text: "Got my oil changed here. Quick service and fair price. Will come back again.",
      photos: [],
      isVerified: true,
      verifiedAt: new Date("2024-01-25"),
      helpfulCount: 2,
      reportCount: 0,
      status: "PUBLISHED",
      createdAt: new Date("2024-01-25"),
      updatedAt: new Date("2024-01-25"),
    },
  ],

  scrapedBusinesses: [
    {
      id: "scraped-1",
      name: "Zabiha Halal Restaurant",
      address: "43433 Mission Blvd",
      city: "Fremont",
      state: "CA",
      zipCode: "94539",
      latitude: 37.5426,
      longitude: -121.9302,
      phone: "(510) 555-7890",
      email: null,
      website: "https://zabiharestaurant.com",
      category: "RESTAURANT",
      description: "Pakistani and Indian halal cuisine. Buffet available daily.",
      sourceUrl: "https://maps.google.com/example",
      scrapedAt: new Date("2024-01-21"),
      claimStatus: "PENDING_REVIEW",
      reviewedAt: null,
      metadata: {
        source: "google_maps",
        confidence: 95,
        signals: ["zabiha", "halal", "pakistani", "muslim owner mention in reviews"],
        suggestedTags: ["HALAL_VERIFIED", "MUSLIM_OWNED"],
        services: ["Dine-in", "Takeout", "Catering"],
      },
    },
    {
      id: "scraped-2",
      name: "Masjid Warithuddin Mohammed",
      address: "5600 Bernal Ave",
      city: "Pleasanton",
      state: "CA",
      zipCode: "94566",
      latitude: 37.6624,
      longitude: -121.8747,
      phone: "(925) 555-1111",
      email: "info@masjidwdm.org",
      website: "https://masjidwdm.org",
      category: "MASJID",
      description: "Community masjid in Pleasanton serving the Tri-Valley area.",
      sourceUrl: "https://zabihah.com/example",
      scrapedAt: new Date("2024-01-22"),
      claimStatus: "PENDING_REVIEW",
      reviewedAt: null,
      metadata: {
        source: "zabihah",
        confidence: 100,
        signals: ["masjid", "islamic center", "prayer times listed"],
        suggestedTags: ["PRAYER_SPACE", "SISTERS_FRIENDLY"],
        services: ["Daily Prayers", "Jummah", "Islamic Education"],
      },
    },
    {
      id: "scraped-3",
      name: "Ahmed's Barber Shop",
      address: "39170 State St",
      city: "Fremont",
      state: "CA",
      zipCode: "94538",
      latitude: 37.5502,
      longitude: -121.9822,
      phone: "(510) 555-2222",
      email: null,
      website: null,
      category: "BARBER_SALON",
      description: "Traditional barber shop with excellent service.",
      sourceUrl: "https://yelp.com/example",
      scrapedAt: new Date("2024-01-20"),
      claimStatus: "REJECTED",
      reviewedAt: new Date("2024-01-21"),
      metadata: {
        source: "yelp",
        confidence: 70,
        signals: ["owner name: Ahmed", "mentions prayer breaks in reviews"],
        suggestedTags: ["MUSLIM_OWNED"],
        services: ["Haircuts", "Beard Trim", "Hot Towel Shave"],
        reviewNote: "Need to verify Muslim ownership - only indicator is owner's name",
        reviewedBy: "user-admin-1",
      },
    },
  ],

  conversations: [
    {
      id: "conv-1",
      businessId: "biz-3",
      customerId: "user-consumer-1",
      subject: "Oil Change Inquiry",
      status: "OPEN",
      lastMessageAt: new Date("2024-01-23T14:30:00"),
      unreadByCustomer: 0,
      unreadByBusiness: 1,
      isBlocked: false,
      createdAt: new Date("2024-01-23T10:00:00"),
      updatedAt: new Date("2024-01-23T14:30:00"),
    },
  ],

  messages: [
    {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "user-consumer-1",
      content: "Hi, how much for an oil change on a Honda Accord?",
      text: "Hi, how much for an oil change on a Honda Accord?",
      attachments: [],
      read: true,
      readAt: new Date("2024-01-23T10:15:00"),
      isFlagged: false,
      createdAt: new Date("2024-01-23T10:00:00"),
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      senderId: "user-business-1",
      content: "Assalamu alaikum! An oil change for your Accord would be $45 including synthetic oil. When would you like to come in?",
      text: "Assalamu alaikum! An oil change for your Accord would be $45 including synthetic oil. When would you like to come in?",
      attachments: [],
      read: true,
      readAt: new Date("2024-01-23T11:00:00"),
      isFlagged: false,
      createdAt: new Date("2024-01-23T10:30:00"),
    },
    {
      id: "msg-3",
      conversationId: "conv-1",
      senderId: "user-consumer-1",
      content: "Great! How about tomorrow at 2pm?",
      text: "Great! How about tomorrow at 2pm?",
      attachments: [],
      read: false,
      isFlagged: false,
      createdAt: new Date("2024-01-23T14:30:00"),
    },
  ],

  bookings: [
    {
      id: "booking-1",
      businessId: "biz-3",
      customerId: "user-consumer-1",
      serviceType: "Oil Change",
      appointmentDate: new Date("2024-01-24T14:00:00"),
      appointmentTime: "14:00",
      duration: 60,
      notes: "Honda Accord 2018. Please use synthetic oil.",
      status: "COMPLETED",
      statusHistory: [
        { status: "PENDING", timestamp: new Date("2024-01-23T15:00:00") },
        { status: "CONFIRMED", timestamp: new Date("2024-01-23T16:00:00") },
        { status: "COMPLETED", timestamp: new Date("2024-01-24T15:00:00") },
      ],
      ownerNotes: "Completed successfully. Customer was happy with the service.",
      reminderSent: true,
      reminderSentAt: new Date("2024-01-24T10:00:00"),
      price: 45,
      paymentStatus: "PAID",
      createdAt: new Date("2024-01-23T15:00:00"),
      updatedAt: new Date("2024-01-24T15:00:00"),
      confirmedAt: new Date("2024-01-23T16:00:00"),
      completedAt: new Date("2024-01-24T15:00:00"),
    },
    {
      id: "booking-2",
      businessId: "biz-3",
      customerId: "user-consumer-1",
      serviceType: "Brake Inspection",
      appointmentDate: new Date("2026-01-15T10:00:00"),
      appointmentTime: "10:00",
      duration: 90,
      notes: "Hearing some squeaking noise when braking.",
      status: "CONFIRMED",
      statusHistory: [
        { status: "PENDING", timestamp: new Date("2026-01-10T09:00:00") },
        { status: "CONFIRMED", timestamp: new Date("2026-01-10T10:30:00") },
      ],
      ownerNotes: "Scheduled for inspection. Will call if major work needed.",
      reminderSent: false,
      price: null,
      paymentStatus: "NOT_REQUIRED",
      createdAt: new Date("2026-01-10T09:00:00"),
      updatedAt: new Date("2026-01-10T10:30:00"),
      confirmedAt: new Date("2026-01-10T10:30:00"),
    },
  ],

  communityPosts: [
    {
      id: "post-1",
      authorId: "user-business-1",
      businessId: "biz-2",
      title: "Ramadan Schedule 2024",
      content: "Assalamu alaikum! We're excited to announce our Ramadan schedule. Taraweeh prayers will be at 9:00 PM daily. Iftar will be provided every evening starting 30 minutes before Maghrib. Volunteers needed for iftar prep - please sign up at the front desk!",
      postType: "ANNOUNCEMENT",
      media: [],
      tags: ["ramadan", "taraweeh", "iftar"],
      viewCount: 156,
      likeCount: 24,
      commentCount: 5,
      shareCount: 8,
      status: "PUBLISHED",
      isPinned: true,
      flagCount: 0,
      publishedAt: new Date("2024-01-20T09:00:00"),
      createdAt: new Date("2024-01-20T09:00:00"),
      updatedAt: new Date("2024-01-20T09:00:00"),
    },
    {
      id: "post-2",
      authorId: "user-consumer-1",
      title: "Looking for Halal Caterer",
      content: "Assalamu alaikum everyone! I'm planning a wedding reception for 200 guests in March. Can anyone recommend a good halal caterer in the Bay Area? Preferably someone who does Pakistani/Indian cuisine. JazakAllah khair!",
      postType: "QUESTION",
      media: [],
      tags: ["wedding", "catering", "recommendations"],
      viewCount: 89,
      likeCount: 12,
      commentCount: 8,
      shareCount: 3,
      status: "PUBLISHED",
      isPinned: false,
      flagCount: 0,
      publishedAt: new Date("2024-01-22T14:30:00"),
      createdAt: new Date("2024-01-22T14:30:00"),
      updatedAt: new Date("2024-01-22T14:30:00"),
    },
    {
      id: "post-3",
      authorId: "user-business-1",
      businessId: "biz-1",
      title: "Weekend Sale - 20% Off Fresh Lamb",
      content: "This weekend only! Get 20% off all fresh lamb cuts. Perfect for your Sunday dinner. Sale runs Friday through Sunday. Come early for best selection!",
      postType: "PROMOTION",
      media: [],
      tags: ["sale", "halal meat", "weekend special"],
      viewCount: 134,
      likeCount: 18,
      commentCount: 3,
      shareCount: 12,
      status: "PUBLISHED",
      isPinned: false,
      flagCount: 0,
      publishedAt: new Date("2024-01-25T08:00:00"),
      createdAt: new Date("2024-01-25T08:00:00"),
      updatedAt: new Date("2024-01-25T08:00:00"),
    },
  ],

  postComments: [
    {
      id: "comment-1",
      postId: "post-1",
      userId: "user-consumer-1",
      content: "MashaAllah! Looking forward to Ramadan at the masjid. Count me in for iftar volunteering!",
      likeCount: 5,
      status: "PUBLISHED",
      createdAt: new Date("2024-01-20T10:30:00"),
      updatedAt: new Date("2024-01-20T10:30:00"),
    },
    {
      id: "comment-2",
      postId: "post-2",
      userId: "user-admin-1",
      content: "Try Zabiha Halal Restaurant on Mission Blvd. They do catering and the food is excellent!",
      likeCount: 8,
      status: "PUBLISHED",
      createdAt: new Date("2024-01-22T15:00:00"),
      updatedAt: new Date("2024-01-22T15:00:00"),
    },
    {
      id: "comment-3",
      postId: "post-2",
      userId: "user-business-1",
      parentId: "comment-2",
      content: "Second this recommendation! We've used them for masjid events.",
      likeCount: 3,
      status: "PUBLISHED",
      createdAt: new Date("2024-01-22T16:00:00"),
      updatedAt: new Date("2024-01-22T16:00:00"),
    },
  ],

  businessViews: [
    {
      id: "view-1",
      businessId: "biz-1",
      userId: "user-consumer-1",
      source: "SEARCH",
      latitude: 37.5485,
      longitude: -121.9886,
      createdAt: new Date("2024-01-18T10:00:00"),
    },
    {
      id: "view-2",
      businessId: "biz-2",
      userId: null,
      source: "MAP",
      latitude: 37.5502,
      longitude: -121.9816,
      createdAt: new Date("2024-01-19T14:30:00"),
    },
  ],
};
